spring.application.name=Enterprise Apps Ilias.BenFodda
# database configuratie
spring.datasource.url=jdbc:h2:mem:illiasdb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
